In [1]:
import numpy as np


In [3]:
a = np.array ([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [16]:
mean_a = np.mean(a, axis=0)

In [17]:
mean_a


array([2. , 8.4])

In [21]:
#### 2

In [18]:
a_centered = a - mean_a

In [20]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [22]:
#### 3

In [82]:
a_1 = np.array([-1, 0, 1, 1, -1])

In [83]:
a_2 = np.array([-2.4, -0.4, 2.6, 1.6, -1.4])

In [84]:
a_centered_sp = np.dot(a_1, a_2)

In [85]:
a_centered_sp

8.0

In [86]:
N1 = 5

In [87]:
a_centered_sp / N1

1.6